Repository humanprotocol/hmt-escrow, pull requests merged in 2020-02, with the labels that each got.

#141 finalizePayouts from public to internal
  contracts/Escrow.sol
Labels: security

#145 Fix nodejs-mem vulnerability WS-2018-0236
  package.json
  yarn.lock
Labels: bug, size/small

#130 fix: update tests to check error messages
  .eslintrc.json
  contracts/Escrow.sol
  docker-compose.yml
  test/Escrow.js
  test/utils/helpers.js
Labels: bug
